version: "3.8"

services:
  frontend:
    depends_on: 
      - backend
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prd
    image: vidly_frontend_v1
    ports:
      - 80:80
    restart: unless-stopped
  backend: 
    depends_on: 
      - db
    build: ./backend
    image: vidly_backend_v1
    ports: 
      - 3001:3001
    environment: 
      DB_URL: mongodb://db/vidly
    command: ./docker-entrypoint.sh
    restart: unless-stopped
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db
    restart: unless-stopped

volumes:
  vidly:
